New mode added for params interpreter

diff --git a/scripts/arduino-esp32-cfg b/scripts/arduino-esp32-cfg
--- a/scripts/arduino-esp32-cfg
+++ b/scripts/arduino-esp32-cfg
@@ -6,10 +6,11 @@ CACHEFILE="arduino-esp32-cfg.cache"
 
 usage() {
     echo "Usage:"
-    echo "	$0 [-h] [-e] [-m SELECTED] [-c EXTRAXFG] [-d DIR] BOARD PARAM"
+    echo "	$0 [-h] [-e | -r] [-m SELECTED] [-c EXTRAXFG] [-d DIR] BOARD PARAM"
     echo "Where:"
     echo "	-h	- show this help"
-    echo "	-e	- return undefined value as empty string"
+    echo "	-e	- return empty string for undefined parameter"
+    echo "	-r	- return escaped by [] parameter name for undefined parameter"
     echo "	-m SELECTED	- board menu selections"
     echo "		example: \"PartitionScheme.min_spiffs CPUFreq.40 UploadSpeed.115200\""
     echo "	-c EXTRACFG	- extra config vars"
@@ -89,6 +90,24 @@ build.fqbn=$(fqbn)"
     mergeCfg "$OVR"
 }
 
+# Get raw param value
+rawVal() {
+    local LINE=`echo "$CFG" | grep "^${1}="`
+    if [ $? -ne 0 ]; then
+        if [ "$OEMPTYOK" = "1" ]; then
+            echo ""
+            return 0
+        elif [ "$OPNAME" = "1" ]; then
+            echo "[${PARAM}]"
+            return 0
+        else
+            echo "${0}: Can't find ${BOARD}.${PARAM}" 1>&2
+            exit 1
+        fi
+    fi
+    echo $LINE | cut -d '=' -f 2-
+}
+
 # Substitute params in dependent param value
 evaluateVal() {
     local STR="$1"
@@ -97,12 +116,7 @@ evaluateVal() {
         [ "$FROM" != "" ]
     do
         local VAR=`echo "$FROM" | sed "s/^{//" | sed "s/}\$//"`
-        if [ `echo "$CFG" | grep -c "^${VAR}="` -eq 0 -a "$OEMPTYOK" = "" ]; then
-            echo "${0}: Can't find '${FROM}' for '${PARAM}' substitution" 1>&2
-            exit 1
-        fi
-        local TO=`echo "$CFG" | grep "^${VAR}=" | cut -d "=" -f 2-`
-        # Not sure which delimiter is safe here, # looks Ok
+        local TO=`rawVal "${VAR}"`
         STR=`echo "$STR" | sed "s#${FROM}#${TO}#g"`
     done
     echo "$STR"
@@ -123,21 +137,23 @@ argFixer() {
 
 # Get options
 OEMPTYOK=""
+OPNAME=""
 MSEL=""
 ECFG=""
 APATH="/usr/local/arduino/hardware/espressif/esp32"
 
-while getopts d:m:c:he opt; do
+while getopts d:m:c:her opt; do
     case $opt in
         d) APATH="$OPTARG"; shift 2 ;;
         m) MSEL="$OPTARG"; shift 2 ;;
         c) ECFG="$OPTARG"; shift 2 ;;
         e) OEMPTYOK="1"; shift ;;
+        r) OPNAME="1"; shift ;;
         *) usage; exit 0 ;;
     esac
 done
 
-if [ $# -lt 2 ]; then
+if [ $# -lt 2 -o "$OPNAME" = "1" -a "$OEMPTYOK" = "1" ]; then
     usage
     exit 1
 fi
@@ -173,16 +189,4 @@ fi
 # Patch for bad compiler args
 argFixer
 
-# Get requested param
-LINE=`echo "$CFG" | grep "^${PARAM}="`
-if [ $? -ne 0 ]; then
-    if [ "$OEMPTYOK" = "1" ]; then
-        echo ""
-        exit 0
-    else
-        echo "${0}: Can't find ${BOARD}.${PARAM}" 1>&2
-        exit 1
-    fi
-fi
-
-evaluateVal "`echo $LINE | cut -d '=' -f 2-`"
+evaluateVal "$(rawVal ${PARAM})"
